"""

Automatically generated by Colab.


# 4,5,6
"""

df12=pd.read_csv('/content/Perfume_Sale.csv')

df12.info()

df12.head()

df12['sold']=df12['sold'].fillna(0)

df12['type']=df12['type'].fillna('Perfume')

df12['available']=df12['available'].fillna(0)

df12['sold']=df12['sold'].astype(int)

df12['available']=df12['available'].astype(int)

df12['brand'] = df12['brand'].fillna('nan')
df12 = df12[~df12['brand'].str.contains(' nan|as shown|as show|as picture shown|As Picture Shows|As picture show|Unbranded|AS PHOTOS|AS SHOWN|AS  SHOWN|AS SHOW|As Show|As Shown|As Show', case=False)]

df12 = df12.reset_index(drop=True)

df12.info()

df12.to_csv('Perfume_Sales.csv')